[workspace]
resolver = "2"
members = ["test-certs"]

[workspace.lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"

[workspace.lints.clippy]
all = "deny"
style = "warn"
perf = "warn"
