reorder_imports = true
error_on_line_overflow = true
error_on_unformatted = true
style_edition = "2024"
overflow_delimited_expr = false
format_code_in_doc_comments = true
imports_granularity = "Crate"